server:
  port: 8110
spring:
  profiles:
    active: dev
  application:
    # 以后要注册到微服务中 起一个 服务名
    name: service-core
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf8
      username: root
      password: root

  # redis放在spring节点下
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#    password: root
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20   #最大连接数，负值表示没有限制，默认8
        max-wait: -1     #最大阻塞等待时间，负值表示没限制 默认 -1
        max-idle: 8      #最大空闲连接，默认8
        min-idle: 0      #最小空闲连接，默认0

mybatis-plus:
  configuration:
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/srb/core/mapper/xml/*.xml
#设置日志级别
logging:
  level:
    root: DEBUG

