server:
  port: 8888

spring:
  profiles:
    active: dev
  application:
    # 以后要注册到微服务中 起一个 服务名
    name: service-core
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf8
      username: root
      password: root
